name: Runtests
on:
  push:
  pull_request:
jobs:
  test:
    name: "Runtests ${{ matrix.julia-version }} - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6', '1.10', '1']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Remove Manifest for Julia 1.6
        if: matrix.julia-version == '1.6'
        shell: bash
        run: |
          echo "Removing top-level Manifest.toml for Julia 1.6 to avoid cross-version resolution issues"
          rm -f Manifest.toml
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
